name: exercise_timer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
version: 1.0.0+1

environment:
  sdk: ">2.12.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.19.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  hive_generator: ^1.1.3
  build_runner: ^2.1.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: EthosNova
      fonts:
        - asset: assets/fonts/EthosNova-Regular.ttf
        - asset: assets/fonts/EthosNova-Italic.ttf
          style: italic
        - asset: assets/fonts/EthosNova-Light.ttf
          weight: 300
        - asset: assets/fonts/EthosNova-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
